// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySiteDAL;

#nullable disable

namespace MySiteDAL.Migrations
{
    [DbContext(typeof(MySiteContext))]
    [Migration("20221122081226_Initial5")]
    partial class Initial5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MySiteBL.Entities.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogId"), 1L, 1);

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            BlogId = 1,
                            url = "http://blogs.packtpub.com/dotnet"
                        },
                        new
                        {
                            BlogId = 2,
                            url = "http://blogs.packtpub.com/dotnetcore"
                        });
                });

            modelBuilder.Entity("MySiteBL.Entities.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"), 1L, 1);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CommentId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            Author = "Packt",
                            Content = "Dotnet 4.7 Released Contents",
                            PostId = 1,
                            Title = "Dotnet 4.7 Released"
                        },
                        new
                        {
                            CommentId = 2,
                            Author = "Packt",
                            Content = "Dotnet 4.8 Released Contents",
                            PostId = 1,
                            Title = "Dotnet 4.8 Released"
                        },
                        new
                        {
                            CommentId = 3,
                            Author = "Packt",
                            Content = "Dotnet 4.7 Released Contents",
                            PostId = 2,
                            Title = "Dotnet 4.7 Released"
                        });
                });

            modelBuilder.Entity("MySiteBL.Entities.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"), 1L, 1);

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PublishedDateTime")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PostId");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            BlogId = 1,
                            Content = "Dotnet 4.7 Released Contents",
                            PublishedDateTime = new DateTime(2022, 11, 22, 9, 12, 26, 484, DateTimeKind.Local).AddTicks(142),
                            Title = "Dotnet 4.7 Released"
                        },
                        new
                        {
                            PostId = 2,
                            BlogId = 1,
                            Content = "Dotnet 4.8 Released Contents",
                            PublishedDateTime = new DateTime(2022, 11, 22, 9, 12, 26, 484, DateTimeKind.Local).AddTicks(183),
                            Title = "Dotnet 4.8 Released"
                        },
                        new
                        {
                            PostId = 3,
                            BlogId = 2,
                            Content = "testContent",
                            PublishedDateTime = new DateTime(2022, 11, 22, 9, 12, 26, 484, DateTimeKind.Local).AddTicks(185),
                            Title = "testTitle"
                        });
                });

            modelBuilder.Entity("MySiteBL.Entities.Comment", b =>
                {
                    b.HasOne("MySiteBL.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("MySiteBL.Entities.Post", b =>
                {
                    b.HasOne("MySiteBL.Entities.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("MySiteBL.Entities.Blog", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("MySiteBL.Entities.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
